# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      windwos_version:
        type: choice
        required: true
        options: 
          - windows-latest
          - windows-2025
          - windows-2022
          - windows-2019

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ github.event.inputs.windwos_version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: enable
        uses: p0we7/test@main
        with:
          ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
          foreground: false

      - name: sleep sometime
        run: Start-Sleep 10
          


